CREATE DATABASE formation;

USE formation;

CREATE TABLE IF NOT EXISTS T_MEM_memberc
(
	MMC_id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	MMC_fk_MME INT NOT NULL,
	MMC_fk_MMY INT NOT NULL,
	MMC_name VARCHAR(50) NOT NULL,
	MMC_surname VARCHAR(50) NOT NULL,
	MMC_login VARCHAR(50) NOT NULL,
	MMC_email VARCHAR(50) NOT NULL,
	MMC_password VARCHAR(200) NOT NULL,
	MMC_dateInscription DATETIME NOT NULL,
	MMC_dateBirth DATE NOT NULL,
	CONSTRAINT fk_MMC_MME FOREIGN KEY (MMC_fk_MME) REFERENCES T_MEM_membere(MME_id),
	CONSTRAINT fk_MMC_MMY FOREIGN KEY (MMC_fk_MMY) REFERENCES T_MEM_membery(MMY_id)
);

CREATE TABLE formation.T_MEM_membere
(
	MME_id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	MME_description VARCHAR(200) NOT NULL
);

CREATE TABLE formation.T_MEM_membery
(
	MMY_id INT PRIMARY KEY AUTO_INCREMENT,
	MMY_description VARCHAR(200)
);


CREATE TABLE T_NEW_newe
(
	NNE_id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	NNE_description VARCHAR(200) NOT NULL
);

CREATE TABLE T_NEW_newc
(
	NNC_id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	NNC_fk_MMC INT NOT NULL,
	NNC_fk_NNE INT NOT NULL,
	NNC_date_creation DATETIME NOT NULL,
	CONSTRAINT fk_NNC_MMC FOREIGN KEY (NNC_fk_MMC) REFERENCES t_mem_memberc (MMC_id),
	CONSTRAINT fk_NNC_NNE FOREIGN KEY (NNC_fk_NNE) REFERENCES t_new_newe (NNE_id)
);


CREATE TABLE T_NEW_newg
(
	NNG_id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	NNG_fk_NNC INT NOT NULL,
	NNG_fk_NNE INT NOT NULL,
	NNG_fk_MMC INT NOT NULL,
	NNG_date_edition DATETIME NOT NULL,
	NNG_title VARCHAR(100) NOT NULL,
	NNG_content TEXT NOT NULL,
	CONSTRAINT fk_NNG_NNC FOREIGN KEY (NNG_fk_NNC) REFERENCES t_new_newc (NNC_id),
	CONSTRAINT fk_NNG_MMC FOREIGN KEY (NNG_fk_MMC) REFERENCES t_mem_memberc (MMC_id),
	CONSTRAINT fk_NNG_NNE FOREIGN KEY (NNG_fk_NNE) REFERENCES t_new_newe (NNE_id)
);



CREATE TABLE formation.T_NEW_commente
(
	NCE_id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	NCE_description VARCHAR(100) NOT NULL
);


CREATE TABLE formation.T_NEW_commentc
(
	NCC_id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	NCC_fk_NCE INT NOT NULL,
	NCC_fk_NNG INT NOT NULL,
	NCC_fk_MMC INT,
	NCC_content TEXT NOT NULL,
	NCC_visitor VARCHAR(100),
	NCC_date DATETIME,
	CONSTRAINT fk_NCC_NCE FOREIGN KEY (NCC_fk_NCE) REFERENCES t_new_commente (NCE_id),
	CONSTRAINT fk_NCC_MMC FOREIGN KEY (NCC_fk_MMC) REFERENCES t_mem_memberc (MMC_id),
	CONSTRAINT fk_NCC_NNG FOREIGN KEY (NCC_fk_NNG) REFERENCES t_new_newg (NNG_id)
);


-- INSERT --
INSERT INTO T_MEM_membere (MME_id,MME_description)
VALUES (1,'INVALID'),(2,'VALID');

INSERT INTO T_NEW_commente (NCE_id,NCE_description)
VALUES (1,'INVALID'),(2,'VALID');

INSERT INTO T_NEW_newe (NNE_id,NNE_description)
VALUES (1,'INVALID'),(2,'VALID');